services:
  muntakkibot:
    build: .
    env_file:
      - .env
    environment:
      IMAGE_DIR: /usr/src/muntakkibot/images
    user: ${UID}:${GID}
    volumes:
      - ${IMAGES}:/usr/src/muntakkibot/images
    command: ["mun_takki_bot"]
